#.travis.yml

language: node_js
node_js:
  - "9.4"

branches:
  only:
    - master
    - false-base

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:  
  
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "default"
  on:
    branch: master
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "false-base"
  on:
    branch: false-base

notifications:
  email:
    on_failure: change
    on_success: change