#.travis.yml

language: node_js
node_js:
  - "9.4"
cache: 
  directories:
    - node_modules
branches:
  only:
    - master
    - false-base

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod


  
deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "default"
    skip_cleanup: true
    on:
      branch: master
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "false-base"
    #use skip_cleanup when using the angular cli -> prevent the dist folder has been removed
    skip_cleanup: true
    on:
      branch: false-base

  

notifications:
  email:
    on_failure: change
    on_success: change